- handlers/cmd.go
- handlers/cmd_test.go
- main.go
- Add the ability to intercept legacy and new (filterable) dataset landing pages
- Checkout, build and run all of the following services: dp-frontend-router, dp-frontend-dataset-controller, dp-frontend-filter-dataset-controller, dp-frontent-renderer all on branch feature/intercept-datasets
- Ensure you have sixteens, zebedee and babbage all running
- Ensure you have go-ns checked out on feature/zebedee client
- navigate your browser to http://localhost:20000/economy/economicoutputandproductivity/productivitymeasures/datasets/labourproductivitybyindustrydivision to test the legacy dataset landing page
- navigate your browser to http://localhost:20000/datasets/1234/editions/5678/versions/2017 to test the new dataset landing page (note this is a completely stubbed page with no frontend model …
> intercept dataset landing pages

- handlers/handlers.go
- mapper/mapper.go
- mapper/mapper_test.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/vendor.json
Extend mapper to map api response data to frontend model for preview and download page
- Start the service on this branch and the renderer on feature/datsetlandingpage-filterable and all the other usual f/end services on cmd-develop
- Verify that when you visit a preview and download page that the page renders correctly (using stubbed api response data)
Anyone
> Extend mapper to map api responses to Preview page model

- codelist/codelist.go
- config/config.go
- data/data.go
- dataset/dataset.go
- dates/dates.go
- dates/dates_test.go
- filter/filter.go
- handlers/clients.go
- handlers/handlers.go
- handlers/validator.go
- main.go
- mapper/mapper.go
- mapper/mapper_test.go
- rules.json
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/listSelector/list-selector.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/rangeSelector/range-selector.go
- vendor/vendor.json
Add the ability to select a time dimension on the CMD journey for CPI and then navigate through the dimension and add/remove values. Note that this uses stubbed versions of the Filter/Dataset apis and may need further integration when plugging in to real versions.
Start the usual services for CMD with the feature/time-dimension branches checked out on the filter-dataset-controller and renderer. You will also need the codelist-api checked out on master as well as cloning this repo https://github.com/mattrout92/stubbed-apis and running the stubbed filter and dataset apis based on the current state of the specs.
Once you have all these services running you should be able to navigate through the time dimension by going to http://localhost:20000/filters/12327673/dimensions and choosing time! …
> Add ability to select time dimension and values within it

- ci/build.yml
- ci/unit.yml
- dates/dates.go
- dates/dates_test.go
- handlers/clients.go
- handlers/dimensions.go
- handlers/filter-overview.go
- handlers/filter-overview_test.go
- handlers/hierarchy.go
- handlers/mock_clients.go
- handlers/preview.go
- mapper/mapper.go
- mapper/mapper_test.go
- vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
- vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
- vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
- vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
- vendor/vendor.json
- Get dimensions from dataset api
- Unstub filter api
To test, you will need to have run the import process
- Ensure the instance id from your import process matches the instance id in your version resource for mongodb
Run these services on the given branches and the rest on cmd-develop
- dp-frontend-dataset-controller `feature/dimensions`
- dp-frontend-filter-dataset-controller `feature/dimensions`
- dp-frontend-renderer `feature/dimensions`
- dp-filter-api `feature/instance-incl-version`
- dp-dataset-api `feature/instance-incl-version`
- dp-dataset-exporter `feature/instance-incl-version`
Verify you can navigate through the filter journey and create a filtered csv at the end
> Unstub dimensions and use latest filter api spec

- mapper/mapper.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/page.go
- vendor/vendor.json
- Use env var to create a taxonomy domain
- Update stubbed downloads to use response from dataset api
Set the environment variable `TAXONOMY_DOMAIN=https://www.ons.gov.uk`
Verify that the taxonomy is fully populated through the cmd journey and redirects you to the live site
Verify when the environment variable is not set then the taxonomy takes you to links on your local environment
> Add taxonomy domain to pages from environment variable

- mapper/mapper.go
- mapper/mapper_test.go
Return to the filter blueprint when you click on Filter Options in breadcrumb on preview page
> Use correct id to return to filter options from preview page

- handlers/dimensions.go
- handlers/time.go
- mapper/mapper.go
- mapper/mapper_test.go
- routes/routes.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/time/time.go
- vendor/vendor.json
- A dimension will default to a flat list if it has less than 20 options
- The range selector no longer exists
- Text updates to the time selector
- If a dimension name does not appear in the dimension name map, then it will
default to the uppercase first letter version of the original name
It will be difficult to test the features on this for the current CPI dataset, due to neither dimension being a flat list. You will notice the text has changed on the time dimension on the labels to reflect UX changes.
Anyone
> Remove range selector and set flat list default

- handlers/filter-overview.go
- mapper/mapper.go
- mapper/mapper_test.go
- Fix taxonomy issues from the beta
- Set environment variable `export TAXONOMY_DOMAIN=https://www.ons.gov.uk`
- Verify that the taxonomy matches that of ons.gov.uk
- Verify that taxonomy successfully redirects on feedback form
- Verify that taxonomy successfully redirects on previous versions list
- Verify that clicking on the change language button redirects you to welsh website homepage
Anyone
> Set taxonomy domain through a method

- routes/routes.go
Fix hierarchy bug
Update filter options screen for mobile
Hierarchy bug:
Navigate 2 levels down in a hierarchy
Add 6 items
Remove 2 from the basket
Click back to previous level
Verify only four in the basket
Mobile:
Verify that the filter options page works for mobile
Anyone
> Update routing to fix a hierarchy remove from basket issue

- handlers/preview.go
- mapper/mapper.go
- routes/routes.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/vendor.json
Updated the mapper and routes to allow for js enhanced creation of download files.
Pull the following branches:
- Renderer - feature/js-enhance-preview
- Filter-controller - feature/js-enhance-preview
- sixteens - feature/js-enhance-preview
- Ensure that the files are generated without the need for a page refresh.
- Disable JS and check that a refresh page button is displayed if the downloads are still building.
- Stop a required service i.e. dp-dataset-exporter-xlsx - Check that an error is displayed after a couple of minutes.
Anyone.
> Updated mapper and routes for the preview page

- mapper/mapper.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/vendor.json
https://trello.com/c/sqMAzb7G/3083-add-unit-of-measurement-to-cmd-preview
added .Data.UnitOfMeasurement to template 
https://github.com/ONSdigital/dp-frontend-renderer/pull/210
p.Data.UnitOfMeasurement to mapper
json:"unit_of_measurement" in PreviewPage struct
https://github.com/ONSdigital/dp-frontend-models/pull/24
https://beta.ons.gov.uk/filter-outputs/32112ac0-6f68-4efc-b03c-083aa5436534
and a filter-outputs page with no unit of measurement
jon or crispin
> Add 'Unit of measurement' to CMD preview

- handlers/preview.go
- Text file is created on the fly in this app, so do not prepend the download service url as is the case with other downloads
Verify logic correct
Anyone
> Don't prepend download service url to text file

- handlers/preview.go
show a more concise preview of filtered dataset - skip columns: (1) data markings, (2) codelists per dimension
you need the referenced PR (see below) on the filter-api
once you're running that, filter a dataset and enjoy fewer columns
anyone
> in preview, skip columns for codelists

- handlers/hierarchy.go
when geography hierarchies didn't contain a root which had children in the predefined list, children was set to an empty list.
fix was to in this case overwrite the children with the original hierarchy API responses' children
check lower level geography hierarchies display correctly ( CCG is a good test for this)
anyone
> Add roots children if geography hierarchy format not satisfied

- handlers/dimensions.go
- handlers/time.go
- call new sortedTime function if rendering a list page for a dimension labelled "time"
- add map of possible month strings and their orders
- sort dimension options by year and month within the year
check times display in filter journey in chronological order
anyone
> Add sortedTime function to order lists of mmm-mmm-yyyy filter options

- handlers/dimensions.go
Add splitCodes check function to return error when code isnt recognized
Previously, the code was panicking as the index was not found when the code never contained the '-' delimiter
check actually works across multiple time list formats (i have tested against cpih, mid year pop and labour market locally - cpih uses the range selector, mid year pop no longer throws an error and just returns years and labour market sorts the weird time format correctly)
anyone
> Add splitCodes check function to return error when code isnt recognized

- mapper/mapper.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/metadata.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/page.go
- vendor/vendor.json
The beta banner now selectively displayed
It should appear on the following types of pages 
- version
- versions list
- edition
- filter journey pages:
-  Age
-  Time
-  Hierarchy
-  Hierarchy Search
-  Preview
-  ListSelector
-  Filter Overview
Checkout the following PRs:
dp-frontend-models: https://github.com/ONSdigital/dp-frontend-models/pull/40
dp-frontend-dataset-controller: https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/118
dp-frontend-renderer: https://github.com/ONSdigital/dp-frontend-renderer/pull/296
Run the CMD stack
Checkout different types of pages, ensure that the Beta banner only appears on CMD pages
> Made the beta banner only appear on the following pages:

- config/config.go
- handlers/filter-overview_test.go
- handlers/handlers.go
- handlers/preview.go
- handlers/search.go
- handlers/search_test.go
- main.go
- mapper/mapper.go
- mapper/mapper_test.go
- routes/routes.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/github.com/kelseyhightower/envconfig/LICENSE
- vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
- vendor/github.com/kelseyhightower/envconfig/README.md
- vendor/github.com/kelseyhightower/envconfig/doc.go
- vendor/github.com/kelseyhightower/envconfig/env_os.go
- vendor/github.com/kelseyhightower/envconfig/env_syscall.go
- vendor/github.com/kelseyhightower/envconfig/envconfig.go
- vendor/github.com/kelseyhightower/envconfig/go.mod
- vendor/github.com/kelseyhightower/envconfig/usage.go
- vendor/vendor.json
- Added feature flag `ENABLE_DATASET_PREVIEW` checking and logic to prevent api calls nad mapping logic. 
- Pass feature flag value to page model, to be passed onto renderer 
- Pull https://github.com/ONSdigital/dp-frontend-renderer/pull/329
- Run `dp-frontend-filter-dataset-controller` with `ENABLE_DATASET_PREVIEW=false` set. 
- Filter a dataset and proceed to the output page. **No** preview should show
Anyone
> Remove dataset preview

- mapper/mapper.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
- vendor/vendor.json
Exposed the `CurrentVersionURL` to the `previewPage` template so that the 'dataset page' link can be updated to return the user to the dataset for the current version rather than the most recent version.
- Pull changes in the feature/current-version-url for the `dp-frontend-models` and `dp-frontend-renderer` repositories as well.
- Navigate to a dataset on the website that has more than one version - select an older version.
-Click 'Filter and download' and then go through steps to apply filters
- Find text, 'Refer to the dataset page for more information...'
- Check that 'dataset page' hyperlink returns to the dataset version you were viewing.
Anyone
> Expose CurrentVersionURL to previewPage template

- handlers/hierarchy.go
- use FilterClient.AddDimensionValues for adding multiple options for a dimension
- the above broke because the form value 'q' was secreted in the form to support its search aspect, so skip passing that param to the filter-api
ensure adding bulk (e.g. 'add all') still works for hierarchies
CMD-aware froods
> change add dimension values to single bulk call, needs to skip 'q' form parameter

- ci/build.yml
- ci/unit.yml
Bump go version to 1.13.8 and fix ci yml files
Use field tag to set ci go version instead of non-functioning tags field
N/A
Anyone
> Bump go version to 1.13.8 and fix ci yml file

- README.md
- config/config.go
- go.mod
- go.sum
- main.go
- routes/routes.go
- Created `/debug` endpoint for pprof, so that developers can easily profile this service in the future.
- Auth-protected the debug endpoints, with identity middleware
- Registered Zebedee checker if debug profiler is enabled
- Unit tests should pass
- If you want, you can verify the `/health` and `/debug/pprof/heap` endpoints with debug enabled and disabled
Anyone
> Added profiler debug endpoint (configurable), with auth protection.

- README.md
- config/config.go
- go.mod
- go.sum
- routes/routes.go
Previously relied on communicating with authenticating service (API) but this may not exist, so use a configurable environment variable to validate an incoming request.
Follow notes in README.md under Profiling:
- Should be able to only gain access to endpoint if the following criteria are met:
- profiling is switched on in application
- environment variable `PPROF_TOKEN` is set to a **non**-empty string
- Request contains header `Authorization` and is equal to "`Bearer + {PPROF_TOKEN}`"
If the above are met, then you can use the following command to create a heap profile of app:
1) `curl <host>:<port>/debug/pprof/heap -H "Authorization: Bearer {generated uuid} > heap.out`
2) `go tool pprof -http=:8080 heap.out` <- without bombarding service this wont contain much information
Anyone
> Add profiling token to validate user access to profiling endpoint

- config/config.go
- main.go
- routes/routes.go
The zebedee client was created to authenticated requests hitting the profiling endpoint. This endpoint does not rely on a auth API and instead controls access via a PPROF_TOKEN. Hence removing zebedee from health checkers and zebedee client as well as config for zebedee url.
Check changes make sense and unit tests still pass
Anyone
> Remove references to zebedee in controller

- mapper/mapper.go
Improve wording of filter options page title
1. Visit CMD dataset
1. Select a filter to add
1. See the page title is just the name of the filter
1. Switch to this branch and see that the page title name of the filter prefixed with `Filter Options -`
Anyone but me
> Fix - Filter options page title

- handlers/preview.go
- Trimmed version prefix from download URL, in previewhandler.
- Make sure code change makes sense (required when proxying API calls through API router)
- Unit tests should pass
Anyone (suggestion: @dandwal )
> Trimmed version prefix in download URL returned by API router

- go.mod
- go.sum
- handlers/time.go
- handlers/time_test.go
- helpers/helpers.go
- helpers/helpers_test.go
- mapper/mapper.go
- mapper/mapper_test.go
- New filter option added that is more accessible
- Squashes form data into the old filter-api format for storage
- Maps the filter-api responses to fulfil the new page model around time selection
- Tests added (but only around work added)
- Models updated
- Work completed under the assumption that all CMD 'time' fields are monthly (can see there is a type in the model declared but is always populated with 'monthly' no matter the dataset.
Check that the whole filter journey works, and that other filters have not broken (especially those involving time as a filter option)
Review in conjunction with:
- https://github.com/ONSdigital/sixteens/pull/244
- https://github.com/ONSdigital/dp-frontend-models/pull/73
- https://github.com/ONSdigital/dp-frontend-renderer/pull/513
> New time filter

- config/config.go
- go.mod
- go.sum
- handlers/age.go
- handlers/age_test.go
- handlers/clients.go
- handlers/common.go
- handlers/common_test.go
- handlers/dimensions.go
- handlers/filter-overview.go
- handlers/filter-overview_test.go
- handlers/handlers.go
- handlers/hierarchy.go
- handlers/hierarchy_test.go
- handlers/mock_clients.go
- handlers/preview.go
- handlers/search_test.go
- handlers/time.go
- handlers/time_test.go
- handlers/update-version.go
- handlers/update-version_test.go
- mapper/mapper.go
- routes/routes.go
Upgraded `dp-api-clients-go` dependency to v1.32.0 in order to match filter API response with `GetDimensions` pagination
Improved efficiency by batch processing where needed, and requesting only the necessary information from APIs where possible:
- getIDNameLookupFromDatasetAPI now gets only the required IDs from dataset API (in batches of `MaxDatasetOptions`) instead of getting all options in batches
- generalised dataset API batch processing (`BatchProcessDimensionOptionsFromDatasetAPI`):
- used to accumulate results in GetDimensionOptionsFromDatasetAPI
- used in dimensions.go addAll to do the dataset.Get+filter.Patch(add) options in batches if needed
- time.go, age.go and dimensions.go now get the count of allValues before deciding if we need to continue, and get all values (in …
> Get Options by IDs from dataset API

- handlers/common.go
Make the check for empty array in get ID Name lookup function more robust by checking for length > 0 as well as nil. This is because sometimes arrays are being instantiated, but still empty
Sense check
Anyone
> check for empty array as well as nil

- go.mod
- go.sum
Upgrade dp-api-clients-go version to make sure the list of IDs is correctly escaped.
Make sure that the version of `dp-api-clients-go` is updated to 1.32.6
Anyone
> Upgrade dp-api-clients-go version to make sure the list of IDs is correctly escaped

- handlers/preview.go
After testing the metadata file generation 'on-the-fly' with >200,000 options per dimension, I didn't see a huge performance impact. In this task the metadata file size calculation is reintroduced using get options in batches
- Get options from dataset API in batches
- Removed errTooManyOptions error
- Information: I tested it locally by artificially returning 200,000 options per dimension for CPIH datasets. The file was around 16MB.
anyone
> used batch processing for metadata file generation

- go.mod
- go.sum
- handlers/age.go
- handlers/clients.go
- handlers/dimensions.go
- handlers/filter-overview.go
- handlers/filter-overview_test.go
- handlers/mock_clients.go
- handlers/preview.go
- handlers/time.go
- handlers/update-version.go
- handlers/update-version_test.go
Needed to upgrade dp-api-clients-go so that we don't assume limit=0 returns all items.
- Upgraded to latest `dp-api-clients-go`, with optional query parameters
- Use limit=0 when we just need the total_count value
- Don't pass query parameters for `get dimensions`
- NOTE: this assumes that we have 20 dimensions max (default limit).
Anyone
> pass query paramters only when necessary

- handlers/preview.go
Rolled back the large metadata file generation implementation, as we think it is better to use download service instead.
Anyone
> rolled back large metadata file size calculation

- go.mod
- go.sum
- handlers/dimensions.go
- handlers/hierarchy.go
- handlers/hierarchy_test.go
- mapper/mapper.go
- mapper/mapper_test.go
- Removed remaining ordering logic for non-hierarchy dimension options
- Use order value returned by hierarchy API to sort the flattened geography items.
- (info): this has been tested locally with the following:
- code-list: `administrative-geography`
- imported dataset: `older-people-sex-ratios`
Anyone
> removed ordering for non-hierarchical dimensions

- handlers/hierarchy.go
Bugfix:
After the changes to support the order from the frontend, a bug was introduced. For example:
https://www.develop.onsdigital.co.uk/filters/1c9c6beb-652c-48b8-90d8-df9c058a8660/dimensions/geography returns a 503 due to a panic caused by a nil ponter.
This PR fixes this issue.
- Make sure code change make sense
Anyone
> Bugfix: check if child is nil

- go.mod
- go.sum
- handlers/filter-overview.go
- handlers/preview.go
- helpers/helpers.go
- helpers/helpers_test.go
- mapper/mapper.go
- mapper/mapper_test.go
- Created check to ensure that an option has been added to the filter
- Added unit tests
- Removed unused code
- Updated dependencies
- Make sure you have [CMD data setup](https://github.com/ONSdigital/dp/blob/main/guides/INSTALLING.md#cmd) and the overall journey working locally to see changes 
- Pull the branch with changes to the [dp-frontend-renderer](https://github.com/ONSdigital/dp-frontend-renderer/tree/fix/error-handling-on-filter-journey-no-js)
- Disable JS
- Check that an error message is shown if you click 'apply filters' with no filters added
- Sanity check
- Unit tests pass
- Check spelling
Anyone but me
> Fix to error handling on filter journey when js is disabled

- mapper/mapper.go
- Update sixteens hash to fix console error for feedback api value
- Fix error for `/dimensions` page
- Check hash matches latest sixteens release
- Run with latest `sixteens`
- Check http://localhost:20001/filters/00dab720-0062-45ec-bc03-c6d5bd381d78/dimensions
- Check dev tools that error is gone
!Me
> Update sixteens hash to fix feedback api value error
