vendor/github.com/ONSdigital/dp-frontend-models/model/contactDetails.go
vendor/github.com/ONSdigital/dp-frontend-models/model/page.go
vendor/github.com/ONSdigital/dp-frontend-models/model/related.go
vendor/vendor.json

The global search was being rendered in the cmd journey. Typo in the page model created the bug.
Pull  this branch and run. Also requires "feature/mobile-search-bug" on the renderer repo and sixteens to be running.
Check that the global search doesn't show on any cmd pages.
http://localhost:20001/jobs/12345/dimensions
Anyone.

Fixed bug with search disabled model and added to vendor

---

dp-frontend-filter-dataset-controller.nomad

- Add nomad plans to service
Lloyd

Add nomad plans for service

---

vendor/github.com/ONSdigital/go-ns/validator/README.md
vendor/github.com/ONSdigital/go-ns/validator/rules.go
vendor/github.com/ONSdigital/go-ns/validator/validate.go
vendor/vendor.json

Add missing vendor dependency

---

data/data.go
filter/filter.go
handlers/clients.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/hierarchy.go
mapper/mapper.go
mapper/mapper_test.go

Update dimension options to match filter api spec

Update dimension options to match updated filter api spec

---

handlers/dimensions.go
mapper/mapper.go
rules.json
vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/rangeSelector/range-selector.go
vendor/vendor.json

- Refactored the range selector for time to include month/year selection
- Fixed minor bug on list selection (was using the wrong id when adding to filter api)
- Start renderer and filter-dataset-controller on feature/refactor-start-end
- Run the rest of cmd services on cmd-develop
- Verify that when you choose the time dimension that you can select month/year from drop down menu successfully
Anyone

Refactor range selector for time to include month years

---

handlers/dimensions.go

Keep previously selected time range

---

README.md
config/config.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/preview.go
handlers/update-version.go
helpers/helpers.go
main.go
mapper/mapper.go
vendor/github.com/ONSdigital/go-ns/clients/clientlog/clientlog.go
vendor/github.com/ONSdigital/go-ns/clients/codelist/codelist.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/github.com/ONSdigital/go-ns/clients/hierarchy/data.go
vendor/github.com/ONSdigital/go-ns/clients/hierarchy/hierarchy.go
vendor/github.com/ONSdigital/go-ns/clients/renderer/renderer.go
vendor/vendor.json

Added production ready logging to the controller
Includes:
- logging out of config on app startup
- logging out when an http status header is set
- updating clients so that clientlog package is used
- log out when healthcheck is conducted
- README updated with latest configs

Production ready logging

---

mapper/mapper.go

The global search bar shows on the preview and download page. 
Run all the services, go through the filter journey to preview. Check that the global search shows.
Anyone.

Enabled global search on the preview and download page

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Order dimensions by id (govendor bump)

Update vendor dependency

---

mapper/mapper.go
vendor/github.com/ONSdigital/go-ns/clients/hierarchy/data.go
vendor/vendor.json

If the top level node has data then display it on the webscreen
Visit goods and services page on CPI
Verify overall index exists
Anyone

Add top level to to hierarchies on website

---

mapper/mapper_test.go

Check the value of the extension in map for unit test

Check the value of the extension in map for unit test

---

handlers/clients.go
handlers/dimensions.go
handlers/mock_clients.go
handlers/preview.go
handlers/time.go
mapper/mapper.go
mapper/mapper_test.go
routes/routes.go
vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/previewPage/preview-page.go
vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/vendor.json

Use the filter api to generate a real preview for the preview and download page
Checkout branch `feature/preview-download` on the filter api
Checkout branch `feature/filter-preview` on dp-frontend-filter-dataset-controller and dp-frontend-renderer
Run other services as normal and generate a filter job. Verify that when you preview and download that the preview dispays correctly on screen
Anyone

Frontend preview for filter job

---

handlers/hierarchy.go

Allow the parent hierarchy to be successfully unticked
Visit the goods and services page
Tick the overall index
Save and Return
Re visit goods and services
Untick overall index
Save and Return
Verify Overall index is not in the basket
Anyone

Allow parent on hierarchy to be unticked

---

README.md

Fix key issue

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go
vendor/vendor.json

Update dataset client in go-ns

---

mapper/mapper.go
mapper/mapper_test.go
vendor/github.com/ONSdigital/dp-frontend-models/model/metadata.go
vendor/vendor.json

Remove any reference to the metadata footer on filter job page data mappings.
1) Checkout out the renderer and dataset controller to `feature/remove-metadata-footer`
2) Check the metadata footer no longers shows and the application builds fine.
Any frontend developer.

Remove metadata footer mapping

---

handlers/filter-overview.go

A fix for non unique dimension options on filter overview page

Fix non unique dimension options on filter overview page

---

handlers/age.go
handlers/update-version.go
mapper/mapper.go
mapper/mapper_test.go

Ensure age and time are ordered correctly when they are rendered as simple list selectors
Using the mid year pop ests dataset, ensure that the list selector renders time in the correct order
Anyone

Ensure age and time are rendered in the correct order

---

handlers/filter-overview.go
handlers/preview.go
mapper/mapper.go

Update to age selector breadcrumb
Ensure latest version url actually points to the latest version
Go to age selector
Verify breadcrumb font is correct size
Verify breadcrumb says filter options
Verify save and return is bold
Anyone

Ensure latest version url actually points to latest version

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/vendor.json

Bug fix for license and prettify downloads

Bug fixes for text file metadata

---

handlers/filter-overview.go
mapper/mapper.go
mapper/mapper_test.go

Sync cmd-master with cmd-develop

Sync cmd-master with cmd-develop

---

mapper/mapper.go

Update filter options page to match ux
https://projects.invisionapp.com/share/CQCR545XV#/screens/265606832
Checkout:
dp-frontend-filter-dataset-controller
dp-frontend-renderer
sixteens
dp-web-tests on `feature/update-filter-options`
Verify page matches UX
Run web tests
Anyone

Update filter options page to match UX

---

handlers/age.go
handlers/clients.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/handlers.go
handlers/handlers_test.go
handlers/hierarchy.go
handlers/preview.go
handlers/time.go
handlers/update-version.go
routes/routes.go
vendor/github.com/ONSdigital/go-ns/clients/codelist/codelist.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/github.com/ONSdigital/go-ns/clients/hierarchy/hierarchy.go
vendor/github.com/ONSdigital/go-ns/clients/renderer/renderer.go
vendor/vendor.json

Add ability to handle 404 responses from various api clients
Checkout:
- dp-frontend-router
- dp-frontend-filter-dataset-controller
- dp-frontend-dataset-controller (feature/handle-not-found)
Visit: http://localhost:20000/datasets/931a8a2a-0dc8-42b6-a884-7b6054ed3b68/editions/Time-series/versions/5
Verify a 404 page is returned
Anyone

Handle when a 404 is returned from various clients

---

handlers/preview.go

Fix for issue with preview handler

---

handlers/age.go
handlers/dimensions.go
handlers/hierarchy.go
handlers/time.go
mapper/mapper.go
mapper/mapper_test.go

Make dimension descriptions available on filter screens
Go to a filter screen and verify the dimension description is there
Anyone

Add dimension descriptions to filter journey

---

handlers/hierarchy.go

Fix issue where hierarchy values were being overwritten

Fix issue where hierarchy values were getting overwritten

---

handlers/preview.go

Fixed a bug where the link was broken to apply the filters to the latest release on the preview page.
Created a partial for the "Not Latest Release" alert that shows on the filter overview and preview pages.
Checkout the renderer on the same branch (bug/latest-release-link).
Check that the alert renders ok and links work as expected.
Anyone.

Updated the latest release link to use the correct id

---

mapper/mapper.go
vendor/github.com/ONSdigital/dp-frontend-models/model/dataset-filter/hierarchy/hierarchy.go
vendor/vendor.json

Updated the mapper to allow us to check if the hierarchy item has data or not.
Checkout the renderer on the same branch (bug/has-data-list-items)
Start a filter journey on pop est and browse the geography dimension - england -> london
Check that the two child items shown do not render a checkbox but allow you to browse the child areas.
Anyone.

Updated mapper to deal with hierarchy list items that don't have data

---

config/config.go
handlers/handlers.go

Use different token for filter api authentication

---

handlers/age.go

Handle when the oldest entered age range value has a plus
Verify when you enter 90+ on mid year pop est age range that it stores your value
Anyone

Handle when the last field in an age range has a plus

---

.travis.yml

Add Travis config for running Go tests on a pull request.
Check Travis file has correct details.
Anyone but me.

Add Travis config for running Go tests

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

- Account for the `next` document on edition when authenticated

Updates to the edition model on the dataset api

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Update dataset api client vendor

---

handlers/hierarchy.go

Pass auth header to filter api on hierarchy build
Verify Logic is correct
Anyone

Send authentication header to getFilterJob on hierarchy build

---

vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
vendor/vendor.json

Change to filter client to handle new downloads structure
It works, go for it
Team B

Use new go-ns filter client (change of download structure)

---

main.go
routes/routes.go
vendor/github.com/ONSdigital/go-ns/LICENSE.md
vendor/github.com/ONSdigital/go-ns/handlers/healthcheck/handler.go
vendor/vendor.json

Change to use empty healthcheck
Review / test
Anyone

Change to use empty healthcheck

---

handlers/preview.go

Update handler to modify json to use configured download service url for preview. This is the handler which the Javascript uses to build the download links on the fly
Verify logic is correct
Anyone

Modify download links json to include configurable download service url

---

vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
vendor/vendor.json

Update vendored filter model for flattened event structure
Review changes
Anyone

Update vendored filter model for flattened event structure

---

mapper/mapper.go
mapper/mapper_test.go

Sort non time / age fields alphabetically in list selector
Run tests/ verify logic correct
Anyone

Sort non-time/age list selectors alphabetically

---

handlers/filter-overview.go
handlers/filter-overview_test.go
handlers/preview.go
mapper/mapper.go
mapper/mapper_test.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Update use of dataset client:
- ToString() not String() for metadata struct
- dimension.ID is now dimension.Name
check everything continues to work 
anyone

Update use of dataset client to use ToString() not String()

---

mapper/mapper.go

Replace Self.ID with Code.ID to match updated API response
Test hierarchy navigation and breadcrumbs work
Anyone

Replace Self.ID with Code.ID to match updated API response

---

vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/vendor.json

In this release:
- Fix links in a hierarchy dimension always routing to the top level of the hierarchy. 
Check that the correct commits are included.
@jondewijones

Beta 1.10.2

---

handlers/hierarchy.go

Update flatten hierarchy to be able to remove elements from list when empty
- create structure to contain list and hardcoded order
- refactor logic to hopefully be easier to follow
- loop through the fixed length array, and only assign to the result elements which are not empty
go to geography filter pages, any elements in the list should be on the top level page, and should not exist under child links (england should be on the top level, not a child of great britain). Elements which have no data and no child links should not be displayed.
(wellbeing and mid-year-pop-est are useful for this)
anyone

Update flatten hierarchy to be able to remove elements from list when empty

---

dp-frontend-filter-dataset-controller.nomad

What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone

Update nomad plan to use docker instead of exec driver

---

handlers/age.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/hierarchy.go
handlers/preview.go
handlers/search.go
handlers/time.go
handlers/update-version.go

add logging to aid in debugging and identifying exactly where failures occured
check logs are useful and have relevant data
anyone

Add logging to all handler failures

---

handlers/dimensions.go

Remove ctx variable and use directly so list selectors will submit again
check filter journey works across all page types
anyone

Remove ctx variable and use directly from request to prevent form parsing bug

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/common/collection.go
vendor/github.com/ONSdigital/go-ns/common/identity.go
vendor/github.com/ONSdigital/go-ns/common/models.go
vendor/github.com/ONSdigital/go-ns/common/rchttp.go
vendor/vendor.json

update datasetAPI client

---

handlers/age.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/hierarchy.go
handlers/preview.go
handlers/search.go
handlers/time.go
handlers/update-version.go
vendor/github.com/ONSdigital/dp-api-clients-go/headers/headers.go
vendor/vendor.json

Using new headers package update `isNotErrNotFound`
Fixed issue of errors being logged when a header was found
Checkout branch. Ensure all places where the token error 'has not been found' were used, have been correctly updated.

Fix incorrectly logging errors on header found.

---

vendor/github.com/ONSdigital/dp-api-clients-go/search/search.go
vendor/vendor.json

Update search api client version in order to use 50 instead of 20 as default search limit
This is a new version of the client already reviewed that has been vendored in.
Search a dimension should no longer be limited to 20 items  
Anyone but me

Update dimension search to 50

---

vendor/github.com/ONSdigital/dp-api-clients-go/search/search.go
vendor/vendor.json

Update search api client version to use 50 instead of 20 as the search limit defaut
Search a dimension containing at least 50 results it should limit to 50
Anyone but me

Beta 1.13.1

---

config/config.go

Nothing except a white space added
Check nothing has changed except a whitespace character

Just a white space for a diff

---

vendor/github.com/ONSdigital/dp-api-clients-go/search/search.go
vendor/github.com/ONSdigital/go-ns/handlers/collectionID/handler.go
vendor/vendor.json

Merging hotfix #178 up to develop.
Anyone.

Merge hotfix back to develop

---

main.go

- Fix error handling for registerCheckers
Anyone.

Fix register checkers error handling

---

README.md
config/config.go
go.mod
go.sum

Updated default healthcheck config values:
- HealthCheckInterval:        30 * time.Second (env `HEALTHCHECK_INTERVAL`)
- HealthCheckCriticalTimeout: 90 * time.Second (env `HEALTHCHECK_CRITICAL_TIMEOUT`)
- Make sure the default config uses the expected values and env vars
Anyone.

Updated default healthcheck config and upgraded to latest dp-healthcheck

---

handlers/hierarchy.go
mapper/mapper.go

- Debug branch 
- Debug code 
Anyone

Moved debugging code to CreateFilterOverview

---

handlers/age.go
handlers/dimensions.go
handlers/filter-overview.go
handlers/hierarchy.go
handlers/preview.go
handlers/search.go
handlers/time.go
mapper/mapper.go
mapper/mapper_test.go

Ensure that the locale is always set
Check language should be and is set

Ensure language is always set

---

handlers/dimensions.go

add missing call to handler func

---

handlers/age.go
handlers/time.go

Calls to handler were doing nothing, they now make use of it
Fixes pages not loading
Check it all works

Calls to handlers were doing nothing

---

handlers/age.go
handlers/dimensions.go
handlers/time.go

Empty pages on the CMD filter journey

Fix for cmd filter journey empty pages

---

handlers/dimensions.go

Fixed error logic to handle case where `err` is not nil. Moved into separate function to improve readability.

fix error logic for get hierarchy

---

handlers/dimensions.go

Removed redundant log messages - no longer needed now that we have identified the issue.

tidy up of fix for live defect, improved log message etc.

---

handlers/age.go
handlers/dimensions.go
handlers/handlers.go
handlers/hierarchy.go
handlers/preview.go
handlers/time.go

Stop using the collection ID from context
- It is passed in the request header and is no longer available in the context.
Sanity check / test
Anyone

Stop using the collection ID from context

---

go.mod
go.sum
handlers/time.go
handlers/time_test.go
helpers/helpers.go
helpers/helpers_test.go
mapper/mapper.go
mapper/mapper_test.go

This has been approved before see https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/pull/233 for more details.
This is a revert of a revert: https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/pull/234
Nothing has changed with this feature/code/PR. This was only reverted as it needed to go out with a renderer change. The renderer required a code change. In order to prevent holding up work on both the renderer and the filter-controller this was reverted on both repositories. They are now ready to be merged back in.

Revert a revert

---

go.mod
go.sum
handlers/time.go
handlers/time_test.go
helpers/helpers.go
helpers/helpers_test.go
mapper/mapper.go
mapper/mapper_test.go

Release 1.28.0
- Check that nothing has slipped in that shouldn't be in here
- Check that everything in here has been PO signed off

Release 1.28.0

---

go.mod
go.sum
mapper/mapper.go
mapper/mapper_test.go
service/service_test.go

- Stop setting ShowFeedbackForm bool in mapper
- Bump version of `dp-frontend-models`
Anyone

Stop setting ShowFeedbackForm bool in mapper

---

go.mod
go.sum

- Upgraded `dp-api-clients-go` version to fix dataset get options by list of IDs.
- Make sure that `dp-api-clients-go` was upgraded to version 1.32.1
Anyone

Update dp-api-clients-go dependency to fix query aramter to filter IDs.

---

handlers/dimensions.go
handlers/filter-overview.go
handlers/hierarchy.go
handlers/search.go

- Added logs in the relevant handlers to validate the performance of the patch and batch processing.
- These logs will be removed after the performance tests finish, and are not supposed to be released to production.
Make sure that only the logs have been added, and nothing else.
Anyone

Added time performance logs to the relevant places

---

Makefile
handlers/dimensions.go
handlers/hierarchy.go

Introduced Time checking for Hierarchy GetRoot and GetChild, for:
- Hierarch
- HierarchyUpdate
- DimensionSelector
make sure changes make sense (to be deleted after performance test in develop is done)
anyone

time hierarchy api GetRoot and GetChild calls

---

handlers/hierarchy.go

initialised GetChildren map in flattenGeography

---

go.mod
go.sum

Bump api client version that removes the URL encoding. Instead, this will be handled in the filter API itself
Sense check
Anyone

bump api client version

---

go.sum
handlers/common.go

escape id query params when we create the option name lookup
anyone

escape id query params when we create the option name lookup

---

handlers/preview.go

- Reintroduced limit=1 (instead of 0) for OutputPage, because we need the label value, not only the count.
- Make sure code change makes sense
- No testing change
Anyone

get one option for output page, as we need it to get the label

---

handlers/preview.go

Revert metadata text size generation on preview page to last working state so that Census filter jobs will preview
Sense check / tests
Anyone

revert metadata text size generation on preview page to last working state

---

ci/build.yml
ci/unit.yml
go.mod

Upgraded go version in go.mod and ci
make sure the right files have been updated
anyone

update go to version to 1.15

---

handlers/hierarchy.go
handlers/hierarchy_test.go
handlers/preview.go

Fixed an incorrect greater-than to less-than and changed the order of a similar check to read consistently.
Added an extra check in case opts.TotalCount returned the wrong value compared to the actual amount of items.
Check everything looks as it is claimed to be. All code-paths have been tested, feel free to test again.
Any dev.

Fix greater-than/less-than switch, add extra check for opts.Totalcount

---

Makefile

Remove mention of rules.json from build target in Makefile

---

go.mod
go.sum
handlers/filter-overview.go
handlers/preview.go
helpers/helpers.go
helpers/helpers_test.go
mapper/mapper.go
mapper/mapper_test.go

- Sanity check
- Make sure nothing's there that shouldn't be
Anyone but me

Release 1.36.0

---

helpers/helpers_test.go

- Refactored tests to be property tests
- Removed redundant tests
All test pass
Anyone but me

Refactoring tests

---

Dockerfile.concourse
ci/build.yml
ci/unit.yml
go.mod
go.sum

As per title
Check container image is available.
Anyone

Update container base to Ubuntu 20.04, update go to v19

---

assets/templates/filter-overview.tmpl
assets/templates/preview.tmpl

Branch maintenance - fold master to develop
Sense check
!me

Fold master to develop

---

go.mod
go.sum
service/service.go

- Add renderror middleware
- Update render version
Anyone

Release 1.40.1

---

README.md
config/config.go
config/config_test.go
main.go

Adds a Batch Timeout environment variable and configures OpenTelemetry to use it.

DIS-160 OpenTelemetry Batch Timeout

---

dp-frontend-filter-dataset-controller.nomad

As per title.
No ONS libs have been updated.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.

Ensure deployments spread over availability zones

---

go.mod
go.sum

Upgrade dp-renderer to fix webkit cookie banner issue.
Check looks ok.
Not me.

Upgrade renderer to fix webkit cookie banner issue
